<?xml version="1.0" encelag="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>ela</string>
	<key>scopeName</key>
	<string>source.ela</string>
	<key>fileTypes</key>
	<array>
		<string>ela</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions_and_declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_escaped_char</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.ela</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
					<key>name</key>
					<string>comment.block.ela</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?((?=//)|(?=#!))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.ela</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ela</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.ela</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&gt;\\\s*\n)</string>
							<key>name</key>
							<string>punctuation.separator.continuation.ela</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>#!</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ela</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.ela</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&gt;\\\s*\n)</string>
							<key>name</key>
							<string>punctuation.separator.continuation.ela</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*/.*\n</string>
					<key>name</key>
					<string>invalid.illegal.stray-comment-end.ela</string>
				</dict>

				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|елси|then|тогда|else|ещё|for|для|while|пока|defer|отложить|return|возврат|матч|switch)\b</string>
					<key>name</key>
					<string>keyword.control.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(break|прерв|continue|продолжать)\b</string>
					<key>name</key>
					<string>keyword.control.ela</string>
				</dict>
				<dict>
          <key>match</key>
          <string>\b(self|себя)\b</string>
          <key>name</key>
          <string>variable.language.ela</string>
        </dict>
				<dict>
					<key>match</key>
					<string>\b(null|нулевой|true|правда|неверим|false)\b</string>
					<key>name</key>
					<string>constant.language.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\d(\d|_)*(.\d(\d|_)*)?)((e|E)(\+|-)?\d+)?[ijk]?\b</string>
					<key>name</key>
					<string>constant.numeric.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0b(0|1|_)+)|(0o(\d|_)+)|(0d(\d|_)+)|(0[xXh](\h|_)+))[ijk]?\b</string>
					<key>name</key>
					<string>constant.numeric.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>---</string>
					<key>name</key>
					<string>constant.numeric.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(alias|struct|структ|enum|перечень|fn|фн|союз|union)\b</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\&mut|\&const|\*mut|\*const|mut|const|где|where|as|как|in|в|is|является|import)\b</string>
					<key>name</key>
					<string>keyword.function.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([#]\s*\b([[:alpha:]_]+[[:alnum:]_]*)\b)</string>
					<key>name</key>
					<string>keyword.tag.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@[^\s;]+</string>
					<key>name</key>
					<string>keyword.tag.ela</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(struct|структ|enum|перечень|union|союз|interface|интерфейс|impl|реализуйте)\b(?:(\{)(\}))?</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$\s*(\b([[:alpha:]_]+[[:alnum:]_]*)\b)</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<!-- Basic Types -->
				<dict>
					<key>match</key>
					<string>\b(s8|s16|s32|s64)\b</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(u8|u16|u32|u64)\b</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(f32|f64)\b</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bool)\b</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(str|String)\b</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(void)\b</string>
					<key>name</key>
					<string>storage.type.ela</string>
				</dict>
			</array>
		</dict>
		<key>functions_and_declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(sizeof|кегль)\b\s*\(</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.function.ela</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[!]?\s*[\(]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.ela</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[:]\s*[:]\s*(struct|union|enum|interface)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.type.ela entity.name.type.ela</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.ela</string>
						</dict>
					</dict>
				</dict>
        <dict>
          <key>match</key>
          <string>\b([A-Z][A-Za-z0-9_]*\b)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.type.ela entity.name.type.ela</string>
            </dict>
          </dict>
        </dict>
				<dict>
					<key>match</key>
					<string>\b(\b[[:alpha:]_]+[[:alnum:]_]*\b)\s*[:]\s*[:]\s*</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.constant.ela entity.name.type.ela</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(\\|[abefnrut"0]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3})</string>
					<key>name</key>
					<string>constant.character.escape.ela</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape.ela</string>
				</dict>
			</array>
		</dict>
    <key>char</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>'</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.char.begin.ela</string>
            </dict>
          </dict>
          <key>end</key>
          <string>'</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.char.end.ela</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.single.ela</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#string_escaped_char</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.ela</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.ela</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.ela</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string_placeholder</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string_escaped_char</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
